apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: oddo
        ports:
        - containerPort: 8069
        env:
        - name: HOST
          value: "db"
        - name: USER
          value: "odoo"
        - name: PASSWORD
          value: "odoo"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
spec:
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
