version: '3'
services:
  odoo:
    image: odoo_custom:1.0.0
    build:
      context: .
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    networks:
      - odoo_network
    volumes:
      - data:/var/lib/odoo
  postgres:
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - odoo_network
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  data:
  db:
networks:
  odoo_network:
